// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.6.1
// source: raft.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RaftTransport_Send_FullMethodName = "/nyxdb.api.RaftTransport/Send"
)

// RaftTransportClient is the client API for RaftTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftTransportClient interface {
	Send(ctx context.Context, opts ...grpc.CallOption) (RaftTransport_SendClient, error)
}

type raftTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftTransportClient(cc grpc.ClientConnInterface) RaftTransportClient {
	return &raftTransportClient{cc}
}

func (c *raftTransportClient) Send(ctx context.Context, opts ...grpc.CallOption) (RaftTransport_SendClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RaftTransport_ServiceDesc.Streams[0], RaftTransport_Send_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &raftTransportSendClient{ClientStream: stream}
	return x, nil
}

type RaftTransport_SendClient interface {
	Send(*RaftMessage) error
	CloseAndRecv() (*RaftAck, error)
	grpc.ClientStream
}

type raftTransportSendClient struct {
	grpc.ClientStream
}

func (x *raftTransportSendClient) Send(m *RaftMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *raftTransportSendClient) CloseAndRecv() (*RaftAck, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RaftAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RaftTransportServer is the server API for RaftTransport service.
// All implementations must embed UnimplementedRaftTransportServer
// for forward compatibility
type RaftTransportServer interface {
	Send(RaftTransport_SendServer) error
	mustEmbedUnimplementedRaftTransportServer()
}

// UnimplementedRaftTransportServer must be embedded to have forward compatible implementations.
type UnimplementedRaftTransportServer struct {
}

func (UnimplementedRaftTransportServer) Send(RaftTransport_SendServer) error {
	return status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedRaftTransportServer) mustEmbedUnimplementedRaftTransportServer() {}

// UnsafeRaftTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftTransportServer will
// result in compilation errors.
type UnsafeRaftTransportServer interface {
	mustEmbedUnimplementedRaftTransportServer()
}

func RegisterRaftTransportServer(s grpc.ServiceRegistrar, srv RaftTransportServer) {
	s.RegisterService(&RaftTransport_ServiceDesc, srv)
}

func _RaftTransport_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftTransportServer).Send(&raftTransportSendServer{ServerStream: stream})
}

type RaftTransport_SendServer interface {
	SendAndClose(*RaftAck) error
	Recv() (*RaftMessage, error)
	grpc.ServerStream
}

type raftTransportSendServer struct {
	grpc.ServerStream
}

func (x *raftTransportSendServer) SendAndClose(m *RaftAck) error {
	return x.ServerStream.SendMsg(m)
}

func (x *raftTransportSendServer) Recv() (*RaftMessage, error) {
	m := new(RaftMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RaftTransport_ServiceDesc is the grpc.ServiceDesc for RaftTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nyxdb.api.RaftTransport",
	HandlerType: (*RaftTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _RaftTransport_Send_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "raft.proto",
}
