nodeID: 1
engine:
  dir: /tmp/nyxdb-node1
  enableDiagnostics: true
cluster:
  clusterMode: true
  nodeAddress: 127.0.0.1:9001
  clusterAddresses:
    - 1@127.0.0.1:9001
    - 2@127.0.0.1:9002
  autoSnapshot: true
  snapshotInterval: 5m
  snapshotThreshold: 2048
  snapshotCatchUpEntries: 128
  # Optional guards for snapshot triggering
  # Trigger when data dir size exceeds this (bytes). 0 to disable.
  snapshotDirSizeThreshold: 0
  # Max duration considered healthy for a single snapshot operation.
  snapshotMaxDuration: 2m
grpc:
  address: 127.0.0.1:10001
observability:
  # Expose Prometheus metrics on this address. Leave empty to disable.
  metricsAddress: 127.0.0.1:2112
