nodeID: 1
engine:
  dir: /tmp/nyxdb-node1
  enableDiagnostics: true
cluster:
  clusterMode: true
  nodeAddress: 127.0.0.1:9001
  clusterAddresses:
    - 1@127.0.0.1:9001
    - 2@127.0.0.1:9002
  autoSnapshot: true
  snapshotInterval: 5m
  snapshotThreshold: 2048
  snapshotCatchUpEntries: 128
  # Optional guards for snapshot triggering
  # Trigger when data dir size exceeds this (bytes). 0 to disable.
  snapshotDirSizeThreshold: 0
  # Max duration considered healthy for a single snapshot operation.
  snapshotMaxDuration: 2m
  # Minimum time between snapshot creation attempts.
  snapshotMinInterval: 2m
  # Maximum allowed applied lag (entries) before snapshot is blocked (0 -> 2x catchup entries).
  snapshotMaxAppliedLag: 0
grpc:
  address: 127.0.0.1:10001
pd:
  # Leave empty to disable PD integration for the MVP setup.
  address: ""
  # Only used when address is provided.
  heartbeatInterval: 2s
observability:
  # Expose Prometheus metrics on this address. Leave empty to disable.
  metricsAddress: ""
  tracing:
    # OTLP collector endpoint (host:port). Leave empty to disable tracing.
    endpoint: ""
    insecure: true
    serviceName: nyxdb-server
    sampleRatio: 1.0
