nodeID: 1
engine:
  dir: /tmp/nyxdb-single
  enableDiagnostics: true
cluster:
  clusterMode: true
  nodeAddress: 127.0.0.1:9001
  clusterAddresses:
    - 1@127.0.0.1:9001
  autoSnapshot: false
  snapshotInterval: 5m
  snapshotThreshold: 2048
  snapshotCatchUpEntries: 128
grpc:
  address: 127.0.0.1:10001
pd:
  address: ""
  heartbeatInterval: 2s
observability:
  metricsAddress: ""
  tracing:
    endpoint: ""
    insecure: true
    serviceName: nyxdb-server
    sampleRatio: 0
